language: python

sudo: required

services:
  - docker

env:
  - DIST=fedora30
#  - DIST=fedoradev
#  - DIST=opensuselp15
  - DIST=opensusetw

# the python here is basically no-op just used for coveralls
python:
  - "3.6"

before_install:
  - docker build -t $DIST -f test/Dockerfile-$DIST .

install:
  - pip install coveralls

script:
  - docker run -v $(pwd):/usr/src/rpmlint/ $DIST python3 setup.py test
  - docker run -v $(pwd):/usr/src/rpmlint/ $DIST flake8

after_success:
  - coverage combine
  # above does not really work as promised
  - sed -i -e "s#/usr/src/rpmlint#$(pwd)#g" .coverage
  - coveralls
