# openSUSE specific configuration

SUIDAllowedPermissions = [
    "lprng",
    "lprng.paranoid",
    "mail-server",
    "mail-server.paranoid",
    "postfix",
    "postfix.paranoid",
    "sendmail",
    "sendmail.paranoid",
    "squid",
    "texlive",
    "texlive.texlive",
    "otrs",  # bsc#1118049
]
