# openSUSE specific configuration

Checks = [
    "AlternativesCheck",
    "AppDataCheck",
    "BinariesCheck",
    "BuildDateCheck",
    'BuildRootCheck',
    "ConfigFilesCheck",
    "CronCheck",
    "DBusPolicyCheck",
    "DBUSServiceCheck",
    'DuplicatesCheck',
    "DocCheck",
    "ErlangCheck",
    "FHSCheck",
    "FilesCheck",
    "IconSizesCheck",
    "I18NCheck",
    "LogrotateCheck",
    "MenuCheck",
    "MenuXDGCheck",
    "MixedOwnershipCheck",
    "PkgConfigCheck",
    "PolkitActionsCheck",
    "PolkitDefaultPrivsOverrideCheck",
    "PolkitRulesAllowedCheck",
    "PostCheck",
    "SignatureCheck",
    "SourceCheck",
    "SpecCheck",
    "SUIDCheck",
    "TagsCheck",
    "ZipCheck",
    "ZyppSyntaxCheck",
]

SUIDAllowedPermissions = [
    "lprng",
    "lprng.paranoid",
    "mail-server",
    "mail-server.paranoid",
    "postfix",
    "postfix.paranoid",
    "sendmail",
    "sendmail.paranoid",
    "squid",
    "texlive",
    "texlive.texlive",
    "otrs",  # bsc#1118049
]
