cronjob-unauthorized-file="""
A cron job file is installed by this package. If the package is
intended for inclusion in any SUSE product please open a bug report to request
review of the package by the security team. Please refer to
https://en.opensuse.org/openSUSE:Package_security_guidelines#audit_bugs for more
information.
"""

cronjob-changed-file="""
A cron job or cron job related file installed by this package changed
in content. Please open a bug report to request follow-up review of the
introduced changes by the security team. Please refer to
https://en.opensuse.org/openSUSE:Package_security_guidelines#audit_bugs for more
information.
"""

cronjob-ghost-file="""
A cron job path has been marked as %ghost file by this package.
This is not allowed as it is impossible to review. Please refer to
https://en.opensuse.org/openSUSE:Package_security_guidelines#audit_bugs for more
information.
"""
