cronjob-unauthorized-file="""
A cron job file is installed by this package.
"""

cronjob-changed-file="""
A cron job or cron job related file installed by this package changed
in content.
"""

cronjob-ghost-file="""
A cron job path has been marked as %ghost file by this package.
"""
