executable-docs="""
Documentation should not be executable."""
package-with-huge-docs="""
More than half the size of your package is documentation.
Consider splitting it into a -doc subpackage."""
package-with-huge-translation="""
More than half the size of your package is language-specific.
Consider splitting it into a -lang subpackage."""
