polkit-unauthorized-rules="""
A polkit rules file installed by this package is not whitelisted in the
polkit-whitelisting package.
"""


polkit-changed-rules="""
A polkit rules file installed by this package changed in content.
"""


polkit-ghost-file="""
This package installs a polkit rule or policy as %ghost file.
"""
