permissions-unauthorized-file="""
Unauthorized file in permissions.
"""



permissions-symlink="""
Permissions handling for symlinks is useless.
"""


permissions-dir-without-slash="""
The entry in the permissions file refers to a directory.
"""


permissions-file-as-dir="""
The entry in the permissions file refers to a directory but the package
actually contains a file.
"""


permissions-incorrect="""
Please use the %attr macro to set the correct permissions.
"""


permissions-incorrect-owner="""
Please use the %attr macro to set the correct ownership.
"""


permissions-file-setuid-bit="""
File is packaged with setuid bit.
"""


permissions-directory-setuid-bit="""
Directory is packaged with setuid bit.
"""


permissions-world-writable="""
File is packages with world writable permissions.
"""


permissions-fscaps="""
Packaging file capabilities is currently not supported. Please use normal
permissions instead.
"""


permissions-missing-postin="""
Please add an appropriate %post section.
"""


permissions-missing-requires="""
Please add 'Requires(phase): permissions'.
"""


permissions-missing-verifyscript="""
Please add a %verifyscript section.
"""


permissions-ghostfile="""
This package installs a permissions file as a %ghost file.
"""
