# Configuration for security checks

[FileDigestLocation.cron]
FollowSymlinks = true
Locations = [
    "/etc/cron.d/",
    "/etc/cron.hourly/",
    "/etc/cron.daily/",
    "/etc/cron.weekly/",
    "/etc/cron.monthly/"
]

[FileDigestLocation.dbus]
FollowSymlinks = true
Locations = [
    "/usr/share/dbus-1/system-services/",
    "/usr/share/dbus-1/system.d/",
    "/etc/dbus-1/system.d/"
]

[FileDigestLocation.polkit]
FollowSymlinks = true
Locations = [
    "/etc/polkit-default-privs.d/",
    "/etc/polkit-1/rules.d/",
    "/usr/share/polkit-1/rules.d/"
]

[FileMetadataCheck."boo#2345"]
package = "foobar"
note = "My note"

[FileMetadataCheck."boo#2345".metadata."/etc/cron.daily/test-me"]
mode = "crw-rw----"
owner = "root"
group = "tty"
device_minor = 1
device_major = 5
