name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup_opensuse:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker: [opensuse/tumbleweed, opensuse/leap]

    container: ${{ matrix.docker }}

    steps:
      - run: zypper -n install
              checkbashisms cpio dash gzip
              bzip2 xz
              binutils glibc glibc-32bit glibc-locale desktop-file-utils
              appstream-glib
              myspell-en_US myspell-cs_CZ
              python3-magic
              python3-pyenchant
              python3-rpm
              python3-base
              python3-setuptools
              python3-pybeam
              python3-pytest
              python3-pytest-cov
              python3-pytest-flake8
              python3-pytest-xdist
              python3-flake8
              python3-flake8-builtins
              python3-flake8-bugbear
              python3-flake8-import-order
              python3-flake8-quotes
              python3-pyxdg
              python3-zstd
              python3-toml
              rpm-build
              sqlite3
      - run: zypper -n install python3-flake8-comprehensions
        if: ${{ matrix.docker == 'opensuse/tumbleweed' }}

  build:
    needs: setup_opensuse
    runs-on: ubuntu-latest
    container: ${{ matrix.docker }}

    steps:
      - run: ls -l

